bitcoind:
    image: lncm/bitcoind:v26.0
    container_name: bitcoin_node
    restart: unless-stopped
    ports:
      - "8333:8333"
      - "8332:8332"
    # Bumped to 8000 since you have 16GB total and are doing a full txindex sync!
    command:
      - -dbcache=4000
    volumes:
      - ${BITCOIN_DATA_PATH}:/data
      - ${BITCOIN_BLOCK_DATA_PATH}:/data/blocks
      - ${BITCOIN_DOTFILE_DATA_PATH}:/data/.bitcoin
    environment:
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_TXINDEX=1
      - BITCOIN_SERVER=1
      - BITCOIN_RPCBIND=0.0.0.0
      - BITCOIN_RPCALLOWIP=0.0.0.0/0
