version: '3.8'

services:
  bitcoind:
    image: lncm/bitcoind:v26.0
    container_name: bitcoin_node
    restart: unless-stopped
    ports:
      - "8333:8333"  # Mainnet P2P
      - "8332:8332"  # RPC Port for Zeus / Portainer connections
    command:
      - "-dbcache=8000"
      - "-par=4"
      - "-assumevalid=000000000000000000021cbf3f9462615436d4df94eb6c9cf1fc2ff769e32a67"
    volumes:
      # Main data directory on the SSD (D:)
      - ${BITCOIN_DATA_PATH}:/data
      # Massive block storage offloaded to the HDD (E:)
      - ${BITCOIN_BLOCK_DATA_PATH}:/data/blocks
      - ${BITCOIN_DOTFILE_DATA_PATH}:/data/.bitcoin
    environment:
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - BITCOIN_TXINDEX=1
      - BITCOIN_SERVER=1
      - BITCOIN_RPCBIND=0.0.0.0
      - BITCOIN_RPCALLOWIP=0.0.0.0/0
