version: '3.8'

services:
  tidarr:
    image: ghcr.io/tidarr/tidarr:latest
    container_name: tidarr
    restart: unless-stopped
    ports:
      - "9422:8080"
    environment:
      - DATABASE_URL=postgres://tidarr_admin:${DB_PASSWORD}@db:5432/tidarr_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${APP_SECRET}
      - NEXTAUTH_URL=http://${SERVER_IP}:9422
    depends_on:
      - db
      - redis
    volumes:
      - D:\Docker\tidarr\app_data:/app/data

  db:
    image: postgres:15-alpine
    container_name: tidarr_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tidarr_admin
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=tidarr_db
    volumes:
      - D:\Docker\tidarr\db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: tidarr_redis
    restart: unless-stopped
    volumes:
      - D:\Docker\tidarr\redis_data:/data
