services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:latest"
    volumes:
      - ${DOCKER_DATA_PATH}\homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    ports:
      - 8123:8123 #optional
    devices:
      - /dev/zigbee:/dev/zigbee
      - /dev/ttyUSB0:/dev/ttyUSB0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s # It takes longer than other services to start
