services:
  jellyfin:
    container_name: jellyfin
    image: "linuxserver/jellyfin"
    volumes:
      - D:/Docker/jellyfin/config:/config
      - D:/Shows:/shows
      - D:/Movies:/movies
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359
      - 1900:1900
