services:
  wireguard:
    container_name: wireguard
    image: "ghcr.io/wg-easy/wg-easy:latest"
    environment:
      - WG_HOST=gt.vpn.knightgil.com
    volumes:
      - D:\Docker\wireguard/etc/wireguard:/etc/wireguard
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp" #optional
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
